maven:3.8.1-openjdk-17-slim

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test Calendar
          caches:
            - maven
          script:
            - cd ./Predjeskovic.Microservice.Calendar
            - mvn clean
            - mvn compile